services:

  postgres:
    image: postgres:17
    container_name: talentmesh-postgres
    environment:
      POSTGRES_USER: talentmesh
      POSTGRES_PASSWORD: talentmesh
      POSTGRES_DB: talentmesh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: